### ISSUE TITLE
Import Error: ImportError: cannot import name 'RawVectorQuery'

### ISSUE THREAD

**Issue by mashhype** [Azure/cognitive-search-vector-pr#117]
not sure what the issue is? Error occurs when running the second cell . Full error: ImportError: cannot import name 'RawVectorQuery' from 'azure.search.documents.models' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/azure/search/documents/models/__init__.py)

**Comment by mashhype** [comment]
Error occurs when running this notebook: https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-sample.ipynb

**Comment by farzad528** [comment]
can you verify you are using azure-search-documents version 11.4.0b11?
https://pypi.org/project/azure-search-documents/11.4.0b11/

Can you run `pip show azure-search-documents` ?

**Comment by mashhype** [comment]
ok, did that, I am using version 11.4.0b8

**Comment by farzad528** [comment]
I'd do `pip install azure-search-documents --pre --upgrade` to use the latest 
OR
`pip install azure-search-documents==11.4.0b11`

**Comment by mashhype** [comment]
ok did that, restarted kernel (Im using AML) and got this error now: cannot import name 'VectorSearchAlgorithmMetric' from 'azure.search.documents.indexes.models' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/azure/search/documents/indexes/models/__init__.py)

**Comment by farzad528** [comment]
This is a known bug, please remove that line from the import statements. In the index definition, you can just use `metric: "cosine"`

**Comment by mashhype** [comment]
Ok, got it working, thank you!

**Comment by cagrimunyas** [comment]
I'm having the same issue. Upgrading from 11.4.0b8 to 11.4.0b11 resolved importing RawVectorQuery error however it now raises `The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Parameters: definition. `  while creating the index. How did you manage to resolve that?
The index creation piece that works on 11.4.0b8 but not on 11.4.0b11:

```
fields.add(
SearchField(
                name="embedding",
                type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                hidden=False,
                searchable=True,
                filterable=False,
                sortable=False,
                facetable=False,
                vector_search_dimensions=1536,
                vector_search_configuration="vector-config"        
                ))

vector_search_config = VectorSearch(algorithm_configurations=[
            HnswVectorSearchAlgorithmConfiguration(
                    name="vector-config",
                    kind="hnsw",
                    parameters={
                        "m": 4,
                        "efConstruction": 400,
                        "efSearch": 1000,
                        "metric": "cosine"
                    }
                )
        ])
index = SearchIndex(name=index_name,
                    fields=fields,
                    vector_search = vector_search_config)
index = self.index_client.create_index(index) # throws error on 11.4.0b11
```

**Comment by mashhype** [comment]
Hi @cagrimunyas, It looks like you may not be using the latest repo? I am comparing the code you have in the cell above to my code, and I see differences. Maybe try doing a `git pull` first and then doing the pip install of that specific version.

**Comment by cagrimunyas** [comment]
> Hi @cagrimunyas, It looks like you may not be using the latest repo? I am comparing the code you have in the cell above to my code, and I see differences. Maybe try doing a `git pull` first and then doing the `pip install` of that specific version.

As I've detailed in the docs issue #120 I followed microsoft learn documentation which recommends to use 11.4.0b8 in vector search scnearios. 
Also cloned this repository from scratch,ran the first cell and install auzre search using `pip install azure-search-documents --pre --quiet` this command installed 11.4.0 so running the following cell in azure search vector python sampe raises : 
`cannot import name 'QueryLanguage' from 'azure.search.documents.models'`

**Comment by mashhype** [comment]
Hi @cagrimunyas, if you look at the earlier comments in this thread, @farzad528 noted that you can use version 11.4.0b11 but then you need to comment out the import of VectorSearchAlgorithmMetric. 

When you go to create your search index, your repo should already have `metric="cosine"` so leave that as-is. Try this and let me know.

**Comment by cagrimunyas** [comment]
Hi @mashhype, I believe I missed that part, also it would be great to reflect that change on notebooks as well. Same trick works on 11.4.0.

**Comment by mashhype** [comment]
Ok, so assuming all is working fine now @cagrimunyas , it wasn't clear from your last comment?

**Comment by cagrimunyas** [comment]
@mashhype Yes, it's working fine. Thank you
